contentmunch:
  auth:
    max-age-in-minutes: 30
    secret: contentmunchcontentmunchcontentmunch!
    cookie:
      name: contentmunch
      same-site: STRICT
      secure: true
      http-only: true
      path: /
    users:
      contentmunch:
        name: Muncher
        username: contentmunch
        email: mail@contentmunch.com
        password: "{noop}password"
        roles: ROLE_USER,ROLE_ADMIN
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
